version: '3.8'

services:
  backend:
    image: new_python
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - '8001:8000'
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    env_file:
      - .env
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}' ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pg-data:/var/lib/postgresql/data
#  migration:
#    image: new_python
#    command: python /app/manage.py migrate --noinput
#    env_file:
#      - .env
#    depends_on:
#      postgres:
#        condition: service_healthy

volumes:
  pg-data: