# Generated by Django 4.1.2 on 2022-11-05 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closingresult',
            name='request',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='closing_result', to='backend.request', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='request',
            name='number',
            field=models.PositiveIntegerField(unique=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='request',
            name='unique_public_services_appeal_number',
            field=models.CharField(blank=True, max_length=27, unique=True, verbose_name='Уникальный номер обращения ГУ (mos.ru)'),
        ),
    ]
