# Generated by Django 4.1.2 on 2022-11-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_user_not_both_null_rename_ods_id_address_ods_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='assessment_quality_work',
            field=models.PositiveSmallIntegerField(max_length=1, verbose_name='Оценка качества выполнения работ'),
        ),
    ]
