# Generated by Django 4.1.2 on 2022-11-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_closingresult_request_alter_request_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='urgency_category_code',
        ),
        migrations.RemoveField(
            model_name='request',
            name='urgency_category_name',
        ),
        migrations.AddField(
            model_name='defect',
            name='urgency_category_code',
            field=models.CharField(default='', max_length=9, verbose_name='Код категории срочности'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defect',
            name='urgency_category_name',
            field=models.CharField(default='', max_length=9, verbose_name='Наименование категории срочности'),
            preserve_default=False,
        ),
    ]
