# Generated by Django 4.1.2 on 2022-11-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_review_assessment_quality_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='assessment_quality_work',
            field=models.PositiveSmallIntegerField(verbose_name='Оценка качества выполнения работ'),
        ),
    ]
