# Generated by Django 4.1.2 on 2022-11-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_request_urgency_category_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refinement',
            name='return_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во возвратов'),
        ),
    ]
