# Generated by Django 4.1.2 on 2022-11-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_refinement_return_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='number',
            field=models.CharField(max_length=11, unique=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='request',
            name='unique_public_services_appeal_number',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Уникальный номер обращения ГУ (mos.ru)'),
        ),
    ]
