# Generated by Django 4.1.2 on 2022-11-06 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_defect_another_term_defect_repeated_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='ods',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='backend.ods', verbose_name='ОДС'),
        ),
        migrations.AlterField(
            model_name='user',
            name='implementing_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='backend.implementingorganization', verbose_name='Организация-исполнитель'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='backend.organization', verbose_name='Организация'),
        ),
    ]
