# Generated by Django 4.1.2 on 2022-11-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_address_ods_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=160, verbose_name='middle name'),
        ),
    ]
